esp32_ble_tracker:
  scan_parameters:
    # Depending on the model and state, BLE advertisements come every 20ms or every 150ms.
    interval: 150ms
    # Run scans continuously so BLE works even when no Wi-Fi component is present.
    continuous: true
